export const SECTORS = [
  { slug: "information-technology", label: "Information Technology", icon: "💻", desc: "Software, hardware, semiconductors, and IT services companies." },
  { slug: "health-care", label: "Health Care", icon: "🏥", desc: "Pharmaceuticals, biotech, medical devices, and health services." },
  { slug: "financials", label: "Financials", icon: "🏦", desc: "Banks, insurance, capital markets, and financial services." },
  { slug: "consumer-discretionary", label: "Consumer Discretionary", icon: "🛍️", desc: "Retail, autos, hotels, and other consumer spending companies." },
  { slug: "industrials", label: "Industrials", icon: "🏭", desc: "Aerospace, defense, machinery, and transportation companies." },
  { slug: "communication-services", label: "Communication Services", icon: "📡", desc: "Media, entertainment, telecom, and internet companies." },
  { slug: "consumer-staples", label: "Consumer Staples", icon: "🛒", desc: "Food, beverages, household products, and personal care." },
  { slug: "energy", label: "Energy", icon: "⚡", desc: "Oil, gas, coal, and renewable energy companies." },
  { slug: "utilities", label: "Utilities", icon: "💡", desc: "Electric, gas, and water utility companies." },
  { slug: "real-estate", label: "Real Estate", icon: "🏢", desc: "REITs and real estate management and development companies." },
  { slug: "materials", label: "Materials", icon: "⛏️", desc: "Chemicals, metals, mining, paper, and construction materials." },
];

export const INDUSTRIES = [
  { slug: "software", label: "Software", sector: "information-technology" },
  { slug: "semiconductors-semiconductor-equipment", label: "Semiconductors & Equipment", sector: "information-technology" },
  { slug: "it-services", label: "IT Services", sector: "information-technology" },
  { slug: "technology-hardware-storage-peripherals", label: "Technology Hardware", sector: "information-technology" },
  { slug: "communications-equipment", label: "Communications Equipment", sector: "information-technology" },
  { slug: "electronic-equipment-instruments-components", label: "Electronic Equipment", sector: "information-technology" },
  { slug: "pharmaceuticals", label: "Pharmaceuticals", sector: "health-care" },
  { slug: "biotechnology", label: "Biotechnology", sector: "health-care" },
  { slug: "health-care-equipment-supplies", label: "Health Care Equipment", sector: "health-care" },
  { slug: "health-care-providers-services", label: "Health Care Services", sector: "health-care" },
  { slug: "life-sciences-tools-services", label: "Life Sciences Tools", sector: "health-care" },
  { slug: "health-care-technology", label: "Health Care Technology", sector: "health-care" },
  { slug: "health-care-reits", label: "Health Care REITs", sector: "health-care" },
  { slug: "banks", label: "Banks", sector: "financials" },
  { slug: "capital-markets", label: "Capital Markets", sector: "financials" },
  { slug: "insurance", label: "Insurance", sector: "financials" },
  { slug: "financial-services", label: "Financial Services", sector: "financials" },
  { slug: "consumer-finance", label: "Consumer Finance", sector: "financials" },
  { slug: "mortgage-real-estate-investment-trusts-reits", label: "Mortgage REITs", sector: "financials" },
  { slug: "specialty-retail", label: "Specialty Retail", sector: "consumer-discretionary" },
  { slug: "hotels-restaurants-leisure", label: "Hotels, Restaurants & Leisure", sector: "consumer-discretionary" },
  { slug: "automobiles", label: "Automobiles", sector: "consumer-discretionary" },
  { slug: "automobile-components", label: "Automobile Components", sector: "consumer-discretionary" },
  { slug: "household-durables", label: "Household Durables", sector: "consumer-discretionary" },
  { slug: "textiles-apparel-luxury-goods", label: "Textiles, Apparel & Luxury Goods", sector: "consumer-discretionary" },
  { slug: "broadline-retail", label: "Broadline Retail", sector: "consumer-discretionary" },
  { slug: "entertainment", label: "Entertainment", sector: "consumer-discretionary" },
  { slug: "leisure-products", label: "Leisure Products", sector: "consumer-discretionary" },
  { slug: "aerospace-defense", label: "Aerospace & Defense", sector: "industrials" },
  { slug: "machinery", label: "Machinery", sector: "industrials" },
  { slug: "ground-transportation", label: "Ground Transportation", sector: "industrials" },
  { slug: "air-freight-logistics", label: "Air Freight & Logistics", sector: "industrials" },
  { slug: "commercial-services-supplies", label: "Commercial Services", sector: "industrials" },
  { slug: "professional-services", label: "Professional Services", sector: "industrials" },
  { slug: "construction-engineering", label: "Construction & Engineering", sector: "industrials" },
  { slug: "building-products", label: "Building Products", sector: "industrials" },
  { slug: "passenger-airlines", label: "Passenger Airlines", sector: "industrials" },
  { slug: "marine-transportation", label: "Marine Transportation", sector: "industrials" },
  { slug: "transportation-infrastructure", label: "Transportation Infrastructure", sector: "industrials" },
  { slug: "industrial-conglomerates", label: "Industrial Conglomerates", sector: "industrials" },
  { slug: "electrical-equipment", label: "Electrical Equipment", sector: "industrials" },
  { slug: "trading-companies-distributors", label: "Trading Companies", sector: "industrials" },
  { slug: "interactive-media-services", label: "Interactive Media Services", sector: "communication-services" },
  { slug: "media", label: "Media", sector: "communication-services" },
  { slug: "wireless-telecommunication-services", label: "Wireless Telecom", sector: "communication-services" },
  { slug: "diversified-telecommunication-services", label: "Diversified Telecom", sector: "communication-services" },
  { slug: "consumer-staples-distribution-retail", label: "Staples Distribution & Retail", sector: "consumer-staples" },
  { slug: "food-products", label: "Food Products", sector: "consumer-staples" },
  { slug: "beverages", label: "Beverages", sector: "consumer-staples" },
  { slug: "household-products", label: "Household Products", sector: "consumer-staples" },
  { slug: "personal-care-products", label: "Personal Care Products", sector: "consumer-staples" },
  { slug: "tobacco", label: "Tobacco", sector: "consumer-staples" },
  { slug: "oil-gas-consumable-fuels", label: "Oil, Gas & Consumable Fuels", sector: "energy" },
  { slug: "energy-equipment-services", label: "Energy Equipment & Services", sector: "energy" },
  { slug: "independent-power-and-renewable-electricity-producers", label: "Independent Power Producers", sector: "utilities" },
  { slug: "electric-utilities", label: "Electric Utilities", sector: "utilities" },
  { slug: "gas-utilities", label: "Gas Utilities", sector: "utilities" },
  { slug: "water-utilities", label: "Water Utilities", sector: "utilities" },
  { slug: "multi-utilities", label: "Multi-Utilities", sector: "utilities" },
  { slug: "diversified-reits", label: "Diversified REITs", sector: "real-estate" },
  { slug: "retail-reits", label: "Retail REITs", sector: "real-estate" },
  { slug: "residential-reits", label: "Residential REITs", sector: "real-estate" },
  { slug: "office-reits", label: "Office REITs", sector: "real-estate" },
  { slug: "industrial-reits", label: "Industrial REITs", sector: "real-estate" },
  { slug: "hotel-resort-reits", label: "Hotel & Resort REITs", sector: "real-estate" },
  { slug: "specialized-reits", label: "Specialized REITs", sector: "real-estate" },
  { slug: "real-estate-management-development", label: "Real Estate Management", sector: "real-estate" },
  { slug: "diversified-reits", label: "Diversified REITs", sector: "real-estate" },
  { slug: "chemicals", label: "Chemicals", sector: "materials" },
  { slug: "metals-mining", label: "Metals & Mining", sector: "materials" },
  { slug: "construction-materials", label: "Construction Materials", sector: "materials" },
  { slug: "containers-packaging", label: "Containers & Packaging", sector: "materials" },
  { slug: "paper-forest-products", label: "Paper & Forest Products", sector: "materials" },
  { slug: "distributors", label: "Distributors", sector: "industrials" },
  { slug: "diversified-consumer-services", label: "Diversified Consumer Services", sector: "consumer-discretionary" },
];

export const INDUSTRY_GROUPS = [
  { slug: "software-services", label: "Software & Services" },
  { slug: "technology-hardware-equipment", label: "Technology Hardware & Equipment" },
  { slug: "semiconductors-semiconductor-equipment", label: "Semiconductors & Equipment" },
  { slug: "pharmaceuticals-biotechnology-life-sciences", label: "Pharmaceuticals, Biotech & Life Sciences" },
  { slug: "health-care-equipment-services", label: "Health Care Equipment & Services" },
  { slug: "banks", label: "Banks" },
  { slug: "financial-services", label: "Financial Services" },
  { slug: "insurance", label: "Insurance" },
  { slug: "capital-goods", label: "Capital Goods" },
  { slug: "commercial-professional-services", label: "Commercial & Professional Services" },
  { slug: "transportation", label: "Transportation" },
  { slug: "consumer-discretionary-distribution-retail", label: "Consumer Discretionary Distribution & Retail" },
  { slug: "consumer-durables-apparel", label: "Consumer Durables & Apparel" },
  { slug: "consumer-services", label: "Consumer Services" },
  { slug: "automobiles-components", label: "Automobiles & Components" },
  { slug: "media-entertainment", label: "Media & Entertainment" },
  { slug: "telecommunication-services", label: "Telecommunication Services" },
  { slug: "food-beverage-tobacco", label: "Food, Beverage & Tobacco" },
  { slug: "household-personal-products", label: "Household & Personal Products" },
  { slug: "consumer-staples-distribution-retail", label: "Consumer Staples Distribution & Retail" },
  { slug: "energy", label: "Energy" },
  { slug: "materials", label: "Materials" },
  { slug: "utilities", label: "Utilities" },
  { slug: "equity-real-estate-investment-trusts-reits", label: "Equity REITs" },
  { slug: "real-estate-management-development", label: "Real Estate Management & Development" },
];

export const SUBINDUSTRIES = [
  "advertising", "aerospace-defense", "agricultural-farm-machinery", "agricultural-products-services",
  "air-freight-logistics", "airport-services", "alternative-carriers", "aluminum",
  "apparel-accessories-luxury-goods", "apparel-retail", "application-software",
  "asset-management-custody-banks", "automobile-manufacturers", "automotive-parts-equipment",
  "automotive-retail", "biotechnology", "brewers", "broadcasting", "broadline-retail",
  "building-products", "cable-satellite", "cargo-ground-transportation", "casinos-gaming",
  "coal-consumable-fuels", "commercial-printing", "commercial-residential-mortgage-finance",
  "commodity-chemicals", "communications-equipment", "computer-electronics-retail",
  "construction-engineering", "construction-machinery-heavy-transportation-equipment",
  "construction-materials", "consumer-electronics", "consumer-finance",
  "copper", "data-center-reits", "data-processing-outsourced-services",
  "diversified-banks", "diversified-capital-markets", "diversified-chemicals",
  "diversified-financial-services", "diversified-metals-mining", "diversified-real-estate-activities",
  "diversified-reits", "diversified-support-services", "drug-retail",
  "electric-utilities", "electrical-components-equipment", "electronic-components",
  "electronic-equipment-instruments", "electronic-manufacturing-services",
  "environmental-facilities-services", "fertilizers-agricultural-chemicals",
  "financial-exchanges-data", "food-distributors", "food-retail", "footwear",
  "forest-products", "gas-utilities", "gold", "health-care-distributors",
  "health-care-equipment", "health-care-facilities", "health-care-reits",
  "health-care-services", "health-care-supplies", "health-care-technology",
  "heavy-electrical-equipment", "home-furnishings", "home-improvement-retail",
  "homebuilding", "homefurnishing-retail", "hotel-resort-reits", "hotels-resorts-cruise-lines",
  "household-appliances", "household-products", "housewares-specialties",
  "human-resource-employment-services", "independent-power-producers-energy-traders",
  "industrial-conglomerates", "industrial-gases", "industrial-machinery-supplies-components",
  "industrial-reits", "integrated-oil-gas", "integrated-telecommunication-services",
  "interactive-home-entertainment", "interactive-media-services",
  "internet-services-infrastructure", "investment-banking-brokerage",
  "it-consulting-other-services", "leisure-facilities", "leisure-products",
  "life-health-insurance", "life-sciences-tools-services", "managed-health-care",
  "marine-transportation", "metal-glass-plastic-containers", "metals-mining",
  "mortgage-reits", "motorcycle-manufacturers", "movies-entertainment",
  "multi-family-residential-reits", "multi-sector-holdings", "multi-utilities",
  "office-reits", "office-services-supplies", "oil-gas-drilling",
  "oil-gas-equipment-services", "oil-gas-exploration-production",
  "oil-gas-refining-marketing", "oil-gas-storage-transportation",
  "other-specialized-reits", "other-specialty-retail", "packaged-foods-meats",
  "paper-plastic-packaging-products-materials", "paper-products", "passenger-airlines",
  "passenger-ground-transportation", "personal-care-products",
  "pharmaceuticals", "precious-metals-minerals", "property-casualty-insurance",
  "publishing", "rail-transportation", "real-estate-development",
  "real-estate-operating-companies", "real-estate-services", "regional-banks",
  "reinsurance", "renewable-electricity", "research-consulting-services",
  "restaurants", "retail-reits", "security-alarm-services",
  "self-storage-reits", "semiconductor-materials-equipment", "semiconductors",
  "silver", "single-family-residential-reits", "soft-drinks-non-alcoholic-beverages",
  "specialized-consumer-services", "specialized-finance", "specialty-chemicals",
  "steel", "systems-software", "technology-distributors",
  "technology-hardware-storage-peripherals", "telecom-tower-reits", "textiles",
  "timber-reits", "tires-rubber", "tobacco", "trading-companies-distributors",
  "transaction-payment-processing-services", "water-utilities",
  "wireless-telecommunication-services",
].map((slug) => ({ slug, label: slug.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ") }));

export function slugToLabel(slug: string) {
  return slug.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

export function getSectorForIndustry(industrySlug: string) {
  return INDUSTRIES.find((i) => i.slug === industrySlug)?.sector ?? null;
}

export function getIndustriesForSector(sectorSlug: string) {
  return INDUSTRIES.filter((i) => i.sector === sectorSlug);
}
